MODIFIER = 1

IMAGE_W = 150 * MODIFIER
IMAGE_H = 225 * MODIFIER


MEAN_WIDTH = 65 * MODIFIER
HEAD_W = int(MEAN_WIDTH // 2.5)


HEAD_X = (IMAGE_W - MEAN_WIDTH) // 2
HEAD_Y = 3 * MODIFIER

W_INCREASE = 5 * MODIFIER

MODEL_INPUT_SIZE = (IMAGE_H, IMAGE_W, 3)
MASK_SIZE = (IMAGE_H, IMAGE_W, 1)

MORPH = 5 * MODIFIER
ALPHA = 0.7

CUM_REDUCE = 0.05
CUM_INCREASE = 0.15

INPAINT_INCREASE = 2 * MODIFIER